utils::globalVariables(c(
  "Hunted", "L1","Natural", "Var1","Var2","ad.an.f.sur","ad.an.m.sur",
  "ad.repro","age", "age.cat", "avg", "avg.percent", "avg.prev", "beta.f",
  "beta.m","buck.doe", "cwd.p", "disease", "env.foi", "f_adult", "f_fawn",
  "fawn.an.sur", "fawn.doe", "fawn.sur.var", "hi","hunt.mort.ad.f",
  "hunt.mort.ad.m", "hunt.mort.fawn","hunt.mort.juv.f", "hunt.mort.juv.m",
  "hunt.p", "hunt.var", "ini.ad.f.prev", "ini.ad.m.prev","ini.fawn.prev",
  "ini.juv.prev","juv.an.sur", "juv.repro", "lo", "m_adult", "m_fawn", "month",
  "n.age.cats", "n.years", "n0", "nat.p", "population", "prev",
  "prevalence", "rel.risk", "repro.var", "scenario", "sex", "sex.age", "sim",
  "sur.var", "theta", "year", "years.to.death", 'CWD', "category", "no", "p",
  "parameter", "percent", "stoch.params", "total", "value", "yes", "beta.ff", 
  "gamma.ff", "gamma.mf", "gamma.fm", "D", "selection.form", "base.juv",
  "stages", "base.adult", "base.old", "r", "s", "beta.f.low", "beta.m.low", 
  "juvs", "adults", "old", "functional.form", "k_max", "k_inflect", 
  "numeric.form", "max.predators", "min.predators", "Predated", "predated.p",
  "Trans.stages", "Transmission", "Sex", "selection", "Age", "prey", "infected",
  "prop", "gamma.mm", "S", "n_inflect"))
