# make sure everything is available to the app.
library(cowplot)
library(dplyr)
library(forcats)
library(ggplot2)
library(ggpubr)
library(ggridges)
library(knitr)
library(magrittr)
library(markdown)
library(plyr)
library(popbio)
library(reshape2)
library(shiny)
library(shinydashboard)
library(tidyr)
library(stringr)