  
## Decision-Support Tool for CWD Management

This application is a decision-support tool for natural resource managers interested in investigating different scenarios associated with chronic wasting disease (CWD). This tool allows the user to enter parameters for deer or elk vital rates, hunting mortality, and disease transmission and the model will plot the total number of individuals, prevalence, age and sex distribution, and how many deaths were natural, hunting or CWD-related. The user can tailor the model to their species and region of interest by modifying the parameters and starting conditions.   

### Model tabs

There are four other pages in this application that can be accessed via the tabs above. The deterministic model, as the name implies, includes no stochasticity. Parameters can be entered and changed using the sliders on the left hand side of the screen and any time a parameter is changed the model will automatically re-run and plot the new results. The stochastic model has the same structure as the deterministic model but includes both environmental and demographic stochasticity. The stochastic model will not automatically re-run every time the parameters are changed. Instead the user must press the "run simulation" button to run the model. Finally there are two comparison tabs that allow for a side-by-side comparison of two different scenarios. The user must press the "run simulation" button for each scenario. Note that the default parameters are initially identical between the two scenarios and need to be changed for the comparison plots to be useful.  

### User inputs  


*Table 1. Parameters included in the models*

|           | Parameter | Symbol | Code name & Default value | Comments |
|-------------- | ---------------- |---------- |------------------ | ------------------------------------|
|State variables | Susceptible  | $S_{i,a}$   | St.f, St.m | $i$ = sex, $a$ = age  |
|                | Infectious | $I_{i,a, j}$ | It.f, It.m | $j$ = infectious sub-category from 1 to 10 |
| |  | |  | |
|Vital rates     | natural survival | $\delta_{i,a}$ |fawn.an.sur = 0.6, juv.an.sur = 0.8, ad.an.f.sur = 0.95, ad.an.m.sur = 0.9 | annual proportions, later converted to monthly |
|                | reproduction      | $\alpha_{a>1}$|fawn.repro = 0, juv.repro = 0.6, ad.repro = 1 | may be greater than one to account for twins | 
|                | hunting mortality | $\kappa_{i,a}$ |hunt.mort.fawn= 0.01, hunt.mort.juv.f= 0.03, hunt.mort.juv.m = 0.03, hunt.mort.ad.f = 0.1, hunt.mort.ad.m = 0.2|  |
|                | disease mortality index | $\rho$ | p = 0.43 | dictates the rate of movement among infectious sub-categories |
| | hunting relative risk | $RR$ | rel.risk = 1 | increase in hunting mortality associated with being CWD positive |
| |  | |  | |
|Transmission    | environmental transmission| $\epsilon$ | env.foi = 0 | annual probability from 0 to 1 |
|                | transmission coefficient | $\beta_{i}$ | beta.f = 0.08, beta.m = 0.08 | direct transmission |
|                | relative male infection  | $\gamma$ | 2 | male transmission = $\beta_m = \beta_f \gamma$|
|                | mixing parameter  | $\theta$ | theta = 1 | $\theta = 1$ is frequency dependent transmission, $\theta = 0$ is density dependent transmission. Can be intermediate. |
| |  | |  | |
|Stochasticity   | vital rate variation  | $\sigma^2$ |repro.var = 0.005, fawn.sur.var = 0.005, sur.var = 0.005, hunt.var = 0.005| variance for the survival, hunting and reproduction rates |
| |  | |  | |
| Intitial conditions | prevalence | | ini.fawn.prev = 0.01, ini.juv.prev = 0.02, ini.ad.f.prev = 0.03, ini.ad.m.prev = 0.03| prevalence at the start of the simulation.
| | population size | | n0 = 1000 | |
| | # of years | | n.years = 10| # of years to run the simulation |
| | # of simulations | | n.sims = 30| # of years to run the simulation |


*Vital rate parameters*   

In the deterministic and stochastic model tabs the user can adjust the model parameters via the sliders on the left-hand side of the page. Parameters are grouped by type in the vital rates, disease, hunting, simulation, and variance tabs. All survival rates are entered as annual probabilities, while reproductive rates are entered as the number of total offspring per female. Note that fawns are defined as <1 year old and juveniles are 1-2 years old. Adults are > 2 years old. 

*Disease parameters*

Indirect transmission is the annual probability of being infected from the environment, which is constant for the duration of the simulation. The direct transmission rate is proportional to $\frac{\beta SI}{N^{\theta}}$, where $\beta$ is the transmission coefficient, $I$ and $N$ are the number of infectious individuals and the total number of individuals.$\theta$ determines how disease transmission is a function of the population size. When $\theta = 0$ disease transmission is a function of the number of infected individuals. When $\theta = 1$ disease transmission is a function of the prevalence (*i.e.* frequency dependent transmission).

While the underlying CWD model functions use $\beta$, in this shiny application we ask the user to input the direct $R_0$ per year, which we define as the expected number of individuals to be infected by an infected individual in a completely susceptible population in one year. This is because $\theta$ has a strong effect on the overall transmission rate, such that a small increase in $\theta$ would require the large decrease $\beta$ to result in a similar prevalence over time. Based on $\theta$ and the per year direct $R_0$ the shiny app then calculates the appropriate $\beta$ value to pass to the model simulation. Note that direct $R_0$ *per year* is not the same as the typical $R_0$ which is based on the entire duration of the infectious period, which may be several years. We used this per year $R_0$ because the traditional $R_0$ is a function of the other user-inputs hunting and natural mortality. The direct per year $R_0$ may be less than one and CWD may still increase in the population if individuals are likely to survive with the disease for many years. Also note that the environmental transmission component is not included in that user-input of the direct $R_0$. Based on these inputs the shiny app calculates $\beta$ for the simulation. 

The model allows for males and females to have differing susceptibility to becoming infected. The user inputs the relative male infections rate, $\gamma$, and $\beta_m = \beta_f\gamma$, so that if $\gamma=1$ then females and males are equally likely to become infected. 

A constant probability of disease induced mortality per time step results in a negative binomial distribution of time until death, whereby most individuals die of disease very quickly and a few survive for a very long time. We used a box-car modeling approach to create a bell-shaped distibution of time until disease induced death where most individuals are likely to survive for a year but few are likely to survive past five. In the box-car approach the infected category is divided into a number of identical sub-categories that an individual must pass through prior to disease-induced mortality occurring. We chose 10 sub-categories. The rate of movement from sub category 1 to 10 then determines the time until death as all individuals die once they leave the 10th category. A probability or proportion of 0.43 moving makes the time to disease-induced death about two years. The user can look at how this index, *p*, of disease mortality is related to time until death in the Plots/Parameters tab. 

The relative hunting risk is the ratio of the probability of an infected vs. uninfected individuals being harvested. When the relative risk is greater than one, infected individuals are more likely likely to be harvested relative to the background prevalence, which may be due to the behavior of infected individuals or management strategies that target hot-spots of infection. 

*Hunting parameters*

The hunting parameters define the annual proportion/probability of each sex and age class that is hunted per year. A value of 0.1 represents 10% of sex and age class. 

*Simulation parameters*

Finally, the initial conditions for CWD prevalence, population size and number of years to run the simulation are available in the simulations tab. 

*Variance parameters* 

The parameters in the stochastic model are the same as the deterministic model with the exception of the number of simulations to be run (Simulation tab) and the variance parameters. The Plots/Parameters tab within the stochastic model page allows the user to view how different mean and variances on natural and hunting mortality affect overall annual survival. 

### Model Structure

The underlying model is a discrete time model with a monthly timestep. Each simulation begins in May with all births occurring in June and all hunting occurring in November. The model tracks sex and ages of individuals in susceptible ($S$) and infectious ($I$) categories to allow for hunting strategies that may target different sex and age groups, and may be preferential to infectious individuals. 

The order of operations in the model is as follows: aging, reproduction, natural mortality, hunting mortality, disease mortality, and disease transmission. Thus, in November when hunting occurs in the model, we assume that the percentage, or probability of,  being hunting is independent of natural mortality and individuals are only hunted if they have first survived other natural causes of death. Since only a small fraction of the population is likely to die of natural causes during one month, this ordering issue is unlikely to be a significant issue. Biologically, different forms of mortality are often correlated, but for modelling purposes we assumed that changing one parameter does not affect any others. 

We assume there is no density dependence in any of the survival or reproduction rates. As a result, host population size will increase or decrease exponentially. However, the intent of the model is to be useful over time spans of five to ten years. To initiate the model we construct an annual time step Leslie matrix population model using the reproduction, natural survival and hunting rates. We then calculate the stable stage distribution and assume that all age classes have equal disease prevalence at the start of the simulation.  

### Plots  

The model sub-samples the monthly time series output to include only one month per year to avoid displaying the within-year variation. The months used for the plots are intended to be in rough agreement with when those data tend to be collected in the field. Total population size is plotted for February. The male:female ratio is sampled in December, and the fawn:doe ratio is taken at the end of the biological year in April. Prevalence data comes from November. The error bars shown in the stochastic plots are the 5% and 95% quantiles, which may not be estimated well if only a few simulations are run. 

$R_0$ is the expected number of individuals that would be infected by a single infectious individual in a completely susceptible population. It has the useful threshold property, such that if it is less than one the disease cannot invade the population, and this can be used to assess different management actions. $R_0$ is an aggregate function of transmission, survival and recovery rates. In these models, $R_0$ is challenging to calculate because transmission is both direct and indirect. In addition, males and females are differentially susceptible. As an approximation, the model calculates as an output $R_0$ for direct transmission only for males and females. Those calculations are provided below the plots. Those $R_0$ calculations differ from the user input of direct $R_0$ per year by incorporating the natural, hunting and disease induced mortality. These calculations also assume that the initial individual is an adult. 

*Comparison plots*

Additional comparison plots are provided at the bottom of the deterministic and stochastic comparison pages. Scenario A comes from the parameters provided on the left-hand side of the page, while Scenario B comes from the right-hand side. Some management actions may have different consequences in the short and long term. The total population size and prevalence are plotted for the last year of the model. However, the number of hunted individuals is shown both for the last year of the model as well as the cumulative amount over the entire simulation. 

Finally, at the bottom of the stochastic comparison page, there are some statistical comparisons of the two scenarios.  

### Citation
This CWD model was developed by the U.S. Geological Survey, Northern Rocky Mountain Science Center, in collaboration with Montana Fish, Wildlife, and Parks. 

The tool may be cited as:

Cross, PC and ES Almberg. 2019. Interactive chronic wasting disease model for scenario planning. URL TBD. DOI: 10.5066/P948SF4Q. 

*Contact:* For technical assistance or to report outages, please contact pcross@usgs.gov

*Disclaimers*: Although these data have been processed successfully on a computer system at the U.S. Geological Survey (USGS), no warranty expressed or implied is made regarding the display or utility of the data for other purposes, nor on all computer systems, nor shall the act of distribution constitute any such warranty. The USGS or the U.S. Government shall not be held liable for improper or incorrect use of the data described and/or contained herein.  

Any use of trade, firm, or product names is for descriptive purposes only and does not imply endorsement by the U.S. Government.