# make sure everything is available to the app.
library(cowplot)
library(dplyr)
library(forcats)
library(ggplot2)
library(ggridges)
library(knitr)
library(magrittr)
library(markdown)
library(plyr)
library(popbio)
library(reshape2)
library(shiny)
library(shinydashboard)
library(tidyr)
library(stringr)

source("compare_det_plots_server.r", local = T)
source("compare_det_plots_server2.r", local = T)
source("compare_det_plotsUI.r", local = T)
source("compare_det_plotsUI2.r", local = T)
source("compare_det_server.r", local = T)
source("compare_detUI.r", local = T)

source("det_mod_server.r", local = T)
source("det_modUI.r", local = T)

source("server.r", local = T)
source("ui.r", local = T)
