library(shiny)
shinyUI(pageWithSidebar(
  headerPanel('SIS Model pulsed reproduction'),
  sidebarPanel(
    h4("Starting Populations:"),
    numericInput("S0", "Number of Susceptibles (S):", 1000),
    numericInput("I0", "Number of Infecteds (I):", 1),
    numericInput("endTime", "# of days:", 3000),
    br(),
    h4("Parameters:"),
    sliderInput("bVal",
                "Transmission coefficient (\\beta):",
                value = 0.01,
                min = 0,
                max = 0.03,
                step = 0.001),
    sliderInput("dVal",
                "Background mortality (\\delta):",
                value = .0005,
                min = 0,
                max = .003,
                step = .0001),
    sliderInput("rVal",
                "Reproduction rate (\\rho):",
                value = 15,
                min = 1,
                max = 20,
                step = 1),
    sliderInput("a0Val",
                "Disease-induced baseline mortality rate (a_0):",
                value = 0.0005,
                min = 0,
                max = .003,
                step = .0001),
    sliderInput("a1Val",
                "Decreasing effect of disease due to N (a_1):",
                value = -0.00005,
                min = -0.0001,
                max = 0,
                step = .00001),
    sliderInput("a2Val",
                "Increasing disease impact due to I (a_2):",
                value = .0001,
                min = 0,
                max = .001,
                step = .00005),
    sliderInput("gVal",
                "Recovery rate (\\gamma):",
                value = .001,
                min = 0,
                max = .02,
                step = .0005),
    numericInput("kVal", "Carrying capacity (k):", 6000),
    br()),
  mainPanel(
    plotOutput('dynamics')
    )
))
